.PHONY: all
all: 
	python generate_alpha_list.py 1000000000 .8 bad1.list
	python generate_alpha_list.py 1000000000 .75 bad2.list
	python generate_alpha_list.py 1000000000 .92 good1.list
	python generate_alpha_list.py 1000000000 .99 good2.list